apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-external-secret
  namespace: default

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: db-secrets
    creationPolicy: Owner

  data:
    - secretKey: db_host
      remoteRef:
        key: nodejs-three-tier-dev/database/credentials-v9
        property: host

    - secretKey: db_user
      remoteRef:
        key: nodejs-three-tier-dev/database/credentials-v9
        property: username

    - secretKey: db_password
      remoteRef:
        key: nodejs-three-tier-dev/database/credentials-v9
        property: password

    - secretKey: db_name
      remoteRef:
        key: nodejs-three-tier-dev/database/credentials-v9
        property: database
