apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  db_host: "nodejs-three-tier-dev-mysql.ce7q4cgws1a0.us-east-1.rds.amazonaws.com"
  db_user: "dbadmin"
  db_password: "]PAx89v(bz8XEZTHKOqr"
  db_name: "devappdb"
