apiVersion: externalsecrets.external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: default   # or whatever namespace your app runs in
spec:
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: nodejs-three-tier-dev/database/credentials-v9
        property: host
    - secretKey: DB_USER
      remoteRef:
        key: nodejs-three-tier-dev/database/credentials-v9
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: nodejs-three-tier-dev/database/credentials-v9
        property: password
    - secretKey: DB_NAME
      remoteRef:
        key: nodejs-three-tier-dev/database/credentials-v9
        property: database
