apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_HOST: "nodejs-three-tier-dev-mysql.ce7q4cgws1a0.us-east-1.rds.amazonaws.com"
  DB_USER: "dbadmin"
  DB_PASSWORD: "th{jGR=tR{YhvRqfIjYL"
  DB_NAME: "appdb"
