name: AWS OIDC Authentication Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage

jobs:
  auth-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for OIDC
      contents: read    # required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug GitHub context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Actor: $GITHUB_ACTOR"

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::901602271390:role/TerraformRepo-GitHubActionsRole
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Print selected environment
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push backend image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/nodejs-three-tier-dev-app:backend-${{ github.sha }} ./three-tier/backend
          docker push ${{ steps.login-ecr.outputs.registry }}/nodejs-three-tier-dev-app:backend-${{ github.sha }}

      - name: Build, tag, and push frontend image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/nodejs-three-tier-dev-app:frontend-${{ github.sha }} ./three-tier/frontend
          docker push ${{ steps.login-ecr.outputs.registry }}/nodejs-three-tier-dev-app:frontend-${{ github.sha }}

      - name: Configure kubectl
        run: aws eks update-kubeconfig --region us-east-1 --name nodejs-three-tier-dev-eks

      - name: Deploy to EKS
        run: |
           kubectl apply -f k8s/dev/db-secrets.yaml
           kubectl apply -f k8s/dev/backend-deployment.yaml
           kubectl apply -f k8s/dev/frontend-deployment.yaml
