name: Terraform Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage

env:
  TF_ROOT: infra/terraform

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: |
          terraform init \
          -backend-config=../environments/${{ github.event.inputs.environment }}/backend.tfvars

      - name: Terraform Validate
        working-directory: ${{ env.TF_ROOT }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_ROOT }}
        run: |
          terraform plan \
          -var-file=../environments/${{ github.event.inputs.environment }}/terraform.tfvars \
          -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/terraform/tfplan

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra/terraform

      - name: Terraform Init
        working-directory: infra/terraform
        run: |
          terraform init \
          -backend-config=../environments/${{ github.event.inputs.environment }}/backend.tfvars

      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply -auto-approve tfplan


      - name: Terraform Destroy
        working-directory: infra/terraform
        run: terraform destroy -auto-approve \-var-file=../environments/${{ github.event.inputs.environment }}/terraform.tfvars
